/*
function ola (){
  console.log ("OLA") //imprimir ola 3x repetir escrever novamente.
  console.log ("OLA")
  console.log ("OLA")
}

ola() //imprimir 2x colocar ola novamente.

*/

/*
function ola (){
  return // não retorna nada
  console.log ("nao chega aqui")
}

*/

/*
function ola (){
  return "ola" // não retorna nada
  console.log ("nao chega aqui")
}

const variavel = ola ()
console.log(variavel)
// vai retorna pois está atribuindo o valor da
//variavel ao retorno da fução//

*/

/*
function soma (A,B) {
  return A + B
}
 
function calculadora(){
  const A = 1
  const B = 2
  const R = soma(10,20)
  return R
}

const resultado = calculadora ()
console.log (resultado)
*/
  
/*
function soma (A,B) {
  return A + B
}
 
function subtracao (A,B) {
  return A-B
}

function calculadora(tipo){
  const A = 1
  const B = 2
  if (tipo === "soma") return soma (A,B)
  else if (tipo ==="subtracao") return subtracao (A,B)
}

const resultado = calculadora ("subtracao")
console.log (resultado)
*/

/*
faça uma função que verifica se o par ou não.

/*
function par (num){
  return num % 2 === 0
}

const ePar = par (3)
console.log(ePar)
*/

/*
exercício 2
mostrar os numeros pares de 0 a 100


for (let i = 0; i <= 100; i++){
  if ((i)) console.log(i)
}
*/