/*
function ola () {
  console.log("OLA")
}

ola ()

const arrowOla = () => {
  console.log("ARROW OLA")
}

arrowOla ()
*/

/*
function ola () {
  console.log("OLA")
}

const arrowOla = () => {
  console.log("ARROW OLA")
}

const soma = (A,B) => {
  return A + B
}

console.log (soma(10,20))
*/
/*
function ola () {
  console.log("OLA")
}

const arrowOla = () => {
  console.log("ARROW OLA")
}

const soma = (A,B) => A + B


console.log (soma(10,20))
*/

/*
function ola () {
  console.log("OLA")
}

const arrowOla = () => {
  console.log("ARROW OLA")
}

const soma = (A,B) => A + B
const ePar = num => num % 2 === 0 
//2 resto é 0 true.
//3 resto é 1 false.
// num é um parametro.

console.log (ePar(2))
console.log (ePar(3))

*/