/*
function Pessoa (nome, sobrenome) {
  let pessoa = {
    nome,
    sobrenome
  }
  pessoa.nomeCompleto = `${nome} ${sobrenome}`
  return pessoa
}

const pessoaA = Pessoa("Heliton","Rodrigues")
const pessoaB = Pessoa("Pedro","Teste")

console.log(pessoaA, pessoaB)
*/
/*
function Pessoa (nome, sobrenome) {
  let pessoa = {
    nome,
    sobrenome
  }
  pessoa.nomeCompleto = `${nome} ${sobrenome}`
  return pessoa
}

const pessoaA = Pessoa("Heliton","Rodrigues")
const pessoaB = Pessoa("Pedro","Teste")

console.log(pessoaA, pessoaB)
console.log (pessoaA.nomeCompleto)
*/